### ISSUE TITLE
running benchmark_kitti.py

### ISSUE THREAD

**Issue by sonamsingh19** [DediGadot/PatchBatch#3]
Hi, when i try to run benchmark_kitti, I get an error. I am not sure where is the problem. Can you help in running a benchmark for kitti?
```
bench_kitti('../../training/image_2/','../../training/flow_noc/','KITTI2015_SPCI',71,255)
Analyzing 000000_10.png 000000_11.png
Calculating descriptors...
Creating NN model_CENTSD_33conv_elu
Traceback (most recent call last):

File "<ipython-input-21-9a2f9cd29ff7>", line 1, in <module>
   bench_kitti('../../training/image_2/','../../training/flow_noc/','KITTI2015_SPCI',71,255)

  File "/home/ms/ssingh/Climate_models/Final_Models/GAN/data/sceneflow/PatchBatch/benchmark_kitti.py", line 22, in bench_kitti
    pb_flow = patchbatch.calc_flow(img1_filename, img2_filename, model_name, None, False)

  File "patchbatch.py", line 155, in calc_flow
    img_descs = calc_descs(img1_filename, img2_filename, model_name, patch_size, batch_size)

  File "patchbatch.py", line 25, in calc_descs
    nn_model, theano_func = NN.get_net_and_funcs(net_name, patch_size, batch_size, weights_filename, eparams_filename)

  File "pb_NN.py", line 103, in get_net_and_funcs
    nn_model = Models.all_models[net_name](patch_size, batch_size)

  File "pb_Models.py", line 169, in model_CENTSD_33conv_elu
    layer = layer_factory(in_layer=layer,layer_type='conv',**layer_params)

  File "pb_Models.py", line 116, in model_CENTSD_33conv

  File "/home/ms/ssingh/anaconda2/lib/python2.7/site-packages/lasagne/layers/input.py", line 56, in __init__
    self.shape, name))

ValueError: Cannot create InputLayer with a non-positive shape dimension. shape=(256, 1, False, False), self.name='l_in0'

```

**Comment by sonamsingh19** [comment]
Another approach I tried by directly calling the method for flow calculation but it doesn't run too:
```
patchbatch.calc_flow('../../training/image_2/000000_10.png','../../training/image_2/000000_11.png','KITTI2012_SPCI',71,255)

  File "<ipython-input-19-29cb9a559d3c>", line 1, in <module>
    patchbatch.calc_flow('../../training/image_2/000000_10.png','../../training/image_2/000000_11.png','KITTI2012_SPCI',71,255)

  File "patchbatch.py", line 155, in calc_flow
  img_descs = calc_descs(img1_filename, img2_filename, model_name, patch_size, batch_size)

  File "patchbatch.py", line 25, in calc_descs
   nn_model, theano_func = NN.get_net_and_funcs(net_name, patch_size, batch_size, weights_filename, eparams_filename)

  File "pb_NN.py", line 111, in get_net_and_funcs
   lasagne.layers.set_all_param_values(nn_model, weights)

  File "/home/ms/ssingh/anaconda2/lib/python2.7/site-packages/lasagne/layers/helper.py", line 518, in set_all_param_values
    (p.get_value().shape, v.shape))

ValueError: mismatch: parameter has shape (2048288,) but value to set has shape (152352,)

```

**Comment by TalSchuster** [comment]
Thank you for noting us.
The patch and batch size were not passed correctly.
It is fixed and the benchmark should work now
